In [ ]:
# Ejercicio 1: ¿Qué diferencia hay entre una Serie y un DataFrame? 
# Una Serie en Pandas es como una columna de datos, mientras que un DataFrame es una estructura de datos bidimensional que se asemeja a una tabla con filas y columnas.

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Ejercicio 2: Es el turno de los DataFrames. Crea un array de dos dimensiones con 4 filas y 3 columnas.

array= np.empty((4,3))

print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:

#1.1 Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_array=pd.DataFrame(array, columns=["España", "Francia", "Italia"])
print(df_array)


   España  Francia  Italia
0     0.0      0.0     0.0
1     0.0      0.0     0.0
2     0.0      0.0     0.0
3     0.0      0.0     0.0


In [40]:

#1.2 Descarga el archivo "medallas" y carga el DataFrame.

df_medallas= pd.read_csv("medallas.csv")

df_medallas



Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [17]:

#1.3 Usando el loc extrae todas las columnas de la fila de Tailandia
df_medallas.loc[7]


País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [18]:

df_medallas.loc[7,:]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [19]:

#1.4. Usando el loc extrae todas las columnas de China e Irán.
df_medallas.loc[[4,9]]


País  Oro  Plata  Bronce
4          Irán  179    181     197
9  China Taipéi   99    144     276

In [20]:

#1.5 Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
df_medallas.loc[[4,9], ["Oro","Plata", "Bronce"]]


Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [24]:
df_medallas.loc[[4,9], "Oro":"Bronce"]

Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [25]:
df_medallas.loc[[4,9], "Oro":]

Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [34]:
df_medallas[df_medallas["País"] == "India"].index

Index([6], dtype='int64')

In [35]:

#1.6. Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5,:]


País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [53]:
print(df_medallas)

   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235


In [44]:

#1.7 Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1:10:2]

Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235

In [51]:

#1.8 Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
df_medallas.iloc[1:10:2, 2:]

Oro  Plata  Bronce
1  1032   1037     985
3   179    181     197
5   154    202     315
7   112    131     240
9    91    120     235

In [ ]:

#1.9 Contesta a las siguientes preguntas:

In [54]:

#¿Qué país consiguió más de 200 medallas de oro?
df_medallas.loc[df_medallas.Oro>200, "País"]

0            China
1            Japón
2    Corea del Sur
Name: País, dtype: object

In [55]:
df_medallas.iloc[list(df_medallas.Oro>200), 1]

0            China
1            Japón
2    Corea del Sur
Name: País, dtype: object

In [ ]:

# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata? ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce? Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país. Momento de trabajar con Series. Contesta a las siguientes preguntas:

# Crea dos listas:

# Una que se llame "valores" que tenga 7 números aleatorios.

# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

# A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

# A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.



Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

Extrae el valor para el índice "lunes"

Extrae el valor para el índice "lunes", "martes" y "miércoles".

Extrae el valor para el índice "lunes" y "domingo".