In [ ]:
# Ejercicio 1: ¿Qué diferencia hay entre una Serie y un DataFrame? 
# Una Serie en Pandas es como una columna de datos, mientras que un DataFrame es una estructura de datos bidimensional que se asemeja a una tabla con filas y columnas.

In [2]:
import pandas as pd
import numpy as np

In [4]:
# Ejercicio 2: Es el turno de los DataFrames. Crea un array de dos dimensiones con 4 filas y 3 columnas.

array= np.empty((4,3))

print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:

#1.1 Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_array=pd.DataFrame(array, columns=["España", "Francia", "Italia"])
print(df_array)


   España  Francia  Italia
0     0.0      0.0     0.0
1     0.0      0.0     0.0
2     0.0      0.0     0.0
3     0.0      0.0     0.0


In [3]:

#1.2 Descarga el archivo "medallas" y carga el DataFrame.

df_medallas= pd.read_csv("medallas.csv")

df_medallas



Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [17]:

#1.3 Usando el loc extrae todas las columnas de la fila de Tailandia
df_medallas.loc[7]


País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [18]:

df_medallas.loc[7,:]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [19]:

#1.4. Usando el loc extrae todas las columnas de China e Irán.
df_medallas.loc[[4,9]]


País  Oro  Plata  Bronce
4          Irán  179    181     197
9  China Taipéi   99    144     276

In [20]:

#1.5 Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
df_medallas.loc[[4,9], ["Oro","Plata", "Bronce"]]


Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [24]:
df_medallas.loc[[4,9], "Oro":"Bronce"]

Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [25]:
df_medallas.loc[[4,9], "Oro":]

Oro  Plata  Bronce
4  179    181     197
9   99    144     276

In [34]:
df_medallas[df_medallas["País"] == "India"].index

Index([6], dtype='int64')

In [35]:

#1.6. Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5,:]


País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [4]:
print(df_medallas)

   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235


In [44]:

#1.7 Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1:10:2]

Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235

In [51]:

#1.8 Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
df_medallas.iloc[1:10:2, 2:]

Oro  Plata  Bronce
1  1032   1037     985
3   179    181     197
5   154    202     315
7   112    131     240
9    91    120     235

In [ ]:

#1.9 Contesta a las siguientes preguntas:

In [54]:

#¿Qué país consiguió más de 200 medallas de oro?
df_medallas.loc[df_medallas.Oro>200, "País"]

0            China
1            Japón
2    Corea del Sur
Name: País, dtype: object

In [55]:
df_medallas.iloc[list(df_medallas.Oro>200), 1]

0            China
1            Japón
2    Corea del Sur
Name: País, dtype: object

In [6]:

# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata? 

df_medallas.loc[(df_medallas.Oro>200) & (df_medallas.Plata>1000), "País"]



1    Japón
Name: País, dtype: object

In [12]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce? 

df_medallas.loc[list((df_medallas.Oro>200) & (df_medallas.Bronce>700)), "País"]

# no estamos seguras si funciona con iLog


0            China
1            Japón
2    Corea del Sur
Name: País, dtype: object

In [15]:
# Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.
df_medallas["Total Medallas"] = df_medallas["Oro"]+df_medallas["Plata"]+df_medallas["Bronce"]

df_medallas


Unnamed: 0             País   Oro  Plata  Bronce  Total Medallas
0           1            China  1473    994     720            3187
1           2            Japón  1032   1037     985            3054
2           3    Corea del Sur   745    663     827            2235
3           4             Irán   179    181     197             557
4           5       Kazajistán   155    158     224             537
5           6            India   154    202     315             671
6           7        Tailandia   132    175     278             585
7           8        Indonesia   112    131     240             483
8           9     China Taipéi    99    144     276             519
9          10  Corea del Norte    91    120     235             446

In [16]:
import numpy as np

In [18]:
import random

In [25]:
# Momento de trabajar con Series. 
# Contesta a las siguientes preguntas:

# Crea dos listas:
# Una que se llame "valores" que tenga 7 números aleatorios.

array = np.random.randint(1, 100, size=7) # es un array

# rand 0 a 1 con decimales

valores = array.tolist()
valores


[77, 49, 2, 65, 62, 71, 15]

In [27]:

# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

indices = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]


In [28]:

# A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.


serie = pd.Series(valores, index = indices)


serie

Lunes        77
Martes       49
Miercoles     2
Jueves       65
Viernes      62
Sabado       71
Domingo      15
dtype: int64

In [ ]:
languages = ['Java', 'Python', 'JavaScript']
versions = [14, 3, 6]

result = zip(languages, versions)
print(list(result))

# Output: [('Java', 14), ('Python', 3), ('JavaScript', 6)]

In [32]:

# A partir de las dos listas anteriores crea un diccionario usando un bucle for. 
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 
# Más información sobre este método aquí.

result = zip(valores, indices)
print(list(result))


[(77, 'Lunes'), (49, 'Martes'), (2, 'Miercoles'), (65, 'Jueves'), (62, 'Viernes'), (71, 'Sabado'), (15, 'Domingo')]


In [34]:
mi_dict = {}
for key, value in zip(indices, valores):
    mi_dict[key] = value
print(mi_dict)

{'Lunes': 77, 'Martes': 49, 'Miercoles': 2, 'Jueves': 65, 'Viernes': 62, 'Sabado': 71, 'Domingo': 15}


In [ ]:
mi_dict = {key: value for key, value in zip(indices, valores)}

In [36]:
mi_dict = dict(zip(indices, valores))
mi_dict

{'Lunes': 77,
 'Martes': 49,
 'Miercoles': 2,
 'Jueves': 65,
 'Viernes': 62,
 'Sabado': 71,
 'Domingo': 15}

In [ ]:
# Crea una Serie con el diccionario creado en el punto anterior.

serie = pd.Series(mi_dict)
serie



Lunes        77
Martes       49
Miercoles     2
Jueves       65
Viernes      62
Sabado       71
Domingo      15
dtype: int64

In [ ]:
# ¿Qué forma tiene esta última Serie?
serie.shape

(7,)

In [40]:
# ¿Qué tipo de datos tiene?

serie.dtype



dtype('int64')

In [41]:
# ¿Qué tamaño tiene?

serie.size



7

In [42]:
# ¿Cuáles son los índices de la Serie?

serie.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='object')

In [51]:
# ¿Y los values?
serie.values
# Extrae el valor para el índice "lunes"
serie[0] 
serie["Lunes"]
# Extrae el valor para el índice "lunes", "martes" y "miércoles".
serie[:3]


/var/folders/fw/63lcqvrj3gj5_78zkmp2ql8r0000gp/T/ipykernel_91263/605119619.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie[0]


Lunes        77
Martes       49
Miercoles     2
dtype: int64

In [53]:
# Extrae el valor para el índice "lunes" y "domingo".
serie[[0,6]]

/var/folders/fw/63lcqvrj3gj5_78zkmp2ql8r0000gp/T/ipykernel_91263/3547376081.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie[[0,6]]


Lunes      77
Domingo    15
dtype: int64